### ISSUE TITLE
Stuck on "GameID"

### ISSUE THREAD

**Issue by sniperstyx** [rumblefrog/source-chat-relay#128]
So in the guide it asks me to use a game server ID that I can't seem to find. Also, I don't see any "Source-Chat-Relay.cfg" in "cfg/sourcemod/". If I was supposed to make the config file, what am I supposed to put in it exactly?

**Comment by rumblefrog** [comment]
Late reply, but I presume you figured it out by now. It's an ID generated by the server, and viewable via r/entities
