### ISSUE TITLE
Binary not running on Windows x64

### ISSUE THREAD

**Issue by Rsslone** [rumblefrog/source-chat-relay#13]
**Describe the bug**
Server binary does not run on windows x64

**To Reproduce**
1. On windowsX64 launch binary
2. See error

**Screenshots**
https://i.imgur.com/3vIPiol.png

**Info (please complete the following information):**
 - OS: Windows 8.1 X64
 - Relay Version [1.1.5]

**Comment by rumblefrog** [comment]
Fixed in v1.1.6 (https://github.com/rumblefrog/source-chat-relay/commit/df143e477b2491a9ebdccc06dad8c83f73e8372a)
