### ISSUE TITLE
Server denied our token, stopping (NMRiH srcds)

### ISSUE THREAD

**Issue by Lunreth** [rumblefrog/source-chat-relay#133]
Plugin fails after getting message "server denied our token, stopping" when having a valid bot token inside config.tom

**Expected behavior**
Plugin should recognize valid token and start

**Info:**
 - Windows 10
 - Sourcemod Version 1.11.0.6914
 - Relay Version 2.20

**Comment by rumblefrog** [comment]
Late reply, but that's an error from Discord. Are you sure you have a valid Discord token?

Going to close for this stale, and reopen if necessary.
