### ISSUE TITLE
Bot messages are ignored.

### ISSUE THREAD

**Issue by kitkaat** [rumblefrog/source-chat-relay#14]
Hi

I was wondering if it would be possible to support other bot's messages to be sent to the csgo server too. 

Practical: I am using your setup to bridge CS:GO to discord, and I use another setup to bridge discord to Riot. The forwarding works from CSGO -> Discord -> Riot. But when I try the other way around : Riot -> Discord -/> CS:GO.

Your bot ignores other bots. Is this intended behaviour, or would you consider allowing other bots' messages to be forwarded?

Kind regards.

**Comment by rumblefrog** [comment]
Hey, checkout v1.2.0.
