### ISSUE TITLE
Config for sourcemod plugin not being generated

### ISSUE THREAD

**Issue by elgato69** [rumblefrog/source-chat-relay#148]
The setup guide says to configure `cfg/sourcemod/Source-Chat-Relay.cfg` but it is not generated when the plugin is loaded. It's also not included in the release zip. Is there a copy i can download from anywhere?

**Comment by rumblefrog** [comment]
Late reply, but that shouldn't be the case; I would check SM log for errors.

I'm going to close this as it's a bit stale and most likely an end-user error.
