### ISSUE TITLE
[Error] Unable to open bot session

### ISSUE THREAD

**Issue by Nerus87** [rumblefrog/source-chat-relay#154]
**Describe the bug**
Can't parse data inside the app:
FATA[0000] Unable to open bot session                    error="strconv.ParseInt: parsing \"1677618691.537\": invalid syntax"

**To Reproduce**
1. Run the server app

**Expected behavior**
Application start working successfully

**Screenshots**
![image](https://user-images.githubusercontent.com/3099926/222193906-ab109194-a6f6-45de-8c44-c61d68cff76f.png)

**Info (please complete the following information):**
 - OS: Ubuntu 22.04 LTS]
 - Relay Version: Current

**Additional context**
Probably something changed on the Discord side

**Comment by rumblefrog** [comment]
Are you still having this problem? My instance still runs smoothly, so it doesn't sound like a Discord issue just yet.

**Comment by Nerus87** [comment]
Yes, now working correctly but still, I have no idea what was the problem.

**Comment by rumblefrog** [comment]
I'm going to pretend Discord had a moment there.

**Comment by Nerus87** [comment]
Now is working, really I don't have any idea, maybe it is some API problem (restrictions on max requests in time?), maybe additional debug messages whould say something?

**Comment by Nerus87** [comment]
To be honest I don't have fucking idea what is wrong with it, it parses something randomly, probably on a DB connection.

**Comment by rumblefrog** [comment]
The error message originates from when opening a session with Discord: https://github.com/rumblefrog/source-chat-relay/blob/735a2c6aa426df152c9ef5cb00c329546eed53e4/server/bot/bot.go#L36

**Comment by Nerus87** [comment]
Now after the container restart works properly, WTF, is stored somewhere in the cache or what?

**Comment by mrnoahfink** [comment]
Same issue after moving to a different house. 
![image](https://github.com/rumblefrog/source-chat-relay/assets/66857858/a489cacb-e3a0-4663-a078-25dbb0751214)

**Comment by mrnoahfink** [comment]
It seems to work fine now. that odd. Perhaps it discord side.

**Comment by sapphonie** [comment]
Can repo...

**Comment by rumblefrog** [comment]
Sappho updated and doesn't seem to encounter this anymore.
