### ISSUE TITLE
"Unable to open bot session" error="strconv.ParseInt: parsing \"1683806882.464\": invalid syntax"

### ISSUE THREAD

**Issue by BringFeel** [rumblefrog/source-chat-relay#155]
Just restart the relay server (Working fine) and start getting that error

"Unable to open bot session" error="strconv.ParseInt: parsing \"1683806882.464\": invalid syntax"

![image](https://github.com/rumblefrog/source-chat-relay/assets/69062690/03f3c176-75c4-4b24-b5ba-6c348c6bdd9b)

**Comment by rumblefrog** [comment]
I'm going to merge this with #154

**Comment by Neoony** [comment]
I only started getting this yesterday after I restarted the relay servers
Updated to the latest and it was fine
I was on v2.1.5-2-gd81f03c until now

weird

Thanks for fixing ❤
