### ISSUE TITLE
Discord bot not responding at commands

### ISSUE THREAD

**Issue by Nerus87** [rumblefrog/source-chat-relay#161]
**Describe the bug**
Hey, I can't configure the bot on Discord, it is not responding to any of the commands on Discord.

**To Reproduce**
1. Create Bot
2. Invite Bot
3. Use commands

**Expected behavior**
The bot should respond to commands

**Screenshots**
![obraz](https://github.com/rumblefrog/source-chat-relay/assets/3099926/8f6d9aa5-df68-48ca-8210-fe1248cea6f9)
![obraz](https://github.com/rumblefrog/source-chat-relay/assets/3099926/98395b9c-3985-4c9f-8b94-4ed3c2f102dc)

**Info (please complete the following information):**
 - OS: Ubuntu 22.04
 - Sourcemod Version 1.11.0.6934
 - Relay Version v2.2.1

**Comment by MAGNAT2645** [comment]
Same

**Comment by MAGNAT2645** [comment]
Fixed by enabling `Message Content Intent` in the bot settings (https://discord.com/developers/applications) 
![изображение](https://github.com/rumblefrog/source-chat-relay/assets/11666918/6c229e8f-e3e5-475b-bef6-9bdf8c215f51)
