### ISSUE TITLE
Disable tagging

### ISSUE THREAD

**Issue by scharfschiesser** [rumblefrog/source-chat-relay#25]
Would it be possible to disable tagging for the bot on Discord? There are users abusing the bot by using a Discord user's ID as their name thus pinging the user on Discord when the message is sent.

**Comment by rumblefrog** [comment]
Since you did not mention any version or provide any config files, I'm going to assume you are using the latest RC and with simple message enabled. 

In that case, this will be fixed in the stable release or the next RC, whichever comes first. In the meantime, it'd be wise to ban them.
