### ISSUE TITLE
FATA[0000] Failed to install Source Chat Relay: readlink /proc/self/exe: no such file or directory

### ISSUE THREAD

**Issue by Elvetiano** [rumblefrog/source-chat-relay#36]
**Describe the bug**
Install error
`FATA[0000] Failed to install Source Chat Relay: readlink /proc/self/exe: no such file or directory`

**To Reproduce**
1. Centos 6

**Comment by rumblefrog** [comment]
Since it cannot locate the bin path using proc/self/exe, you'll just have to install it yourself if you want a service via systemctl, etc. Or just launch it in a detached screen.

**Comment by Elvetiano** [comment]
I get no screen from launching it detached. How can i install it manualy? centos 6 init.d start/stop/restart logic

**Comment by rumblefrog** [comment]
Create a service file for the service manager of your choice, plenty of guides if you search for them.

**Comment by Elvetiano** [comment]
what abot this exqampla
`#!/bin/bash
#/etc/rc.d/init.d/Source-Chat-Relay



start() {
        echo -n "Starting Source-Chat-Relay... "
        nohup  ./bin/server -service start &
        touch /var/lock/subsys/Source-Chat-Relay
        return 0
}

stop() {
        echo -n "Shutting down Source-Chat-Relay... "
        nohup ./bin/server -service stop &
        rm -f /var/lock/subsys/Source-Chat-Relay
        return 0
}

case "$1" in
    start)
        start
        ;;
    stop)
        stop
        ;;
    status)
        ;;
    restart)
        stop
        start
        ;;
    reload)
        ;;
    *)
        echo "Usage: Source-Chat-Relay {start|stop|status|reload|restart}"
 exit 1
        ;;
esac
exit $?`

**Comment by rumblefrog** [comment]
I have no idea what that is or intends to do, you'll need to view the manual for your distribution.
