### ISSUE TITLE
message not working 

### ISSUE THREAD

**Issue by kiozix** [rumblefrog/source-chat-relay#38]
Hello 

on srcds i have 
Source Chat Relay: Successfully authenticated
on discord i have 
![image](https://user-images.githubusercontent.com/31328799/91244768-7898cf80-e74d-11ea-9c2d-601e83b40a06.png)
on source chat relay ui i have 
![image](https://user-images.githubusercontent.com/31328799/91244814-982ff800-e74d-11ea-855e-8f058dfcfa51.png)

finaly no message work i try say test and test ingame and discord test not message work help please

**Comment by rumblefrog** [comment]
Please read the documentation, receive and send channels are virtual channels, and non-binding to foreign entities.

**Comment by kiozix** [comment]
Ok but i follow your doc not work help me befor closing

**Comment by rumblefrog** [comment]
As explicitly stated in the documentation and the thread. The issue tracker is exclusively for tracking features, bugs, and other code-related instances. Please read the documentation.
