### ISSUE TITLE
As explicitly stated in the documentation and the thread. The issue tracker is exclusively for tracking features, bugs, and other code-related instances. Please read the documentation.

### ISSUE THREAD

**Issue by kiozix** [rumblefrog/source-chat-relay#39]
As explicitly stated in the documentation and the thread. The issue tracker is exclusively for tracking features, bugs, and other code-related instances. Please read the documentation.

_Originally posted by @rumblefrog in https://github.com/rumblefrog/source-chat-relay/issues/38#issuecomment-680433018_

how to make it work if you are not able to make an understandable docs change out create video tutorials i try same of your docs and not working this is a bug

**Comment by rumblefrog** [comment]
Reading is hard.
