### ISSUE TITLE
Filter not working in Windows. 

### ISSUE THREAD

**Issue by WOLFA22** [rumblefrog/source-chat-relay#87]
The server is installed as a Windows service, installed according to the instructions. 

Account: NT/System.

Bug: The Regex filter does not work if the relay server is running as a Windows service.
Specifically: Skips commands when they are strictly prescribed in the filter.txt file, the file itself is in the folder with the server.

[filter.txt](https://github.com/rumblefrog/source-chat-relay/files/7331243/filter.txt)
The filter file is attached.

**Comment by rumblefrog** [comment]
Late reply, but I'm going to assume you figured it out. If not, provide your config file as well.
