### ISSUE TITLE
Disable relaying emotes/emoji from discord to gameserver and fix colors for CSGO

### ISSUE THREAD

**Issue by cytrus224** [rumblefrog/source-chat-relay#9]
https://imgur.com/a/o6BunI3

**Comment by rumblefrog** [comment]
Thank you, I'll work on this.

**Comment by rumblefrog** [comment]
Should be addressed in v0.0.6 pre-release (https://github.com/rumblefrog/source-chat-relay/commit/a9c7a578b24fce61174fd5b3726cda8ffa0463bd)
