### ISSUE TITLE
emojis are probably broken

### ISSUE THREAD

**Issue by StShAzzy** [rumblefrog/source-chat-relay#98]
this is a oddity that seems to be a bug

send any screenshot or discord default emoji

i expected it to work by sending ";thinking;", instead of showing up as "" a.k.a None or nothing showing any text at all and the color code failing and instead displaying CCCCCC in the server chat

 - OS: Windows 10 Pro (10.0.18362)
 - Sourcemod Version 1.11.0.6858
 - Relay Version v2.1.5-2-gd81f03c
 
 there's another bug surrounding the same thing, emojis from the server show up but they get an ID by their side so :LOL:<ID>: would be displayed to the server
 
 the solution for this problem in my opinion is ignore images completely and instead for the emojis interpret them as plain text would be fine i guess
![image](https://user-images.githubusercontent.com/90798128/155858903-30b7b7bf-2ee0-486d-a8f3-3285334d50d1.PNG)
this first one is a attempt to send a image
![discord default emoji](https://user-images.githubusercontent.com/90798128/155858911-10aec21a-a1e0-4461-a96d-9a310cae79ad.PNG)
this second one is an attempt to send a stock discord emoji
![non-default emoji](https://user-images.githubusercontent.com/90798128/155858919-b9a59184-f12b-4e57-a8e6-cfeac88cf771.PNG)
and this one is a non-stock emoji

**Comment by rumblefrog** [comment]
Late reply, but noted for v3. It's not something I actively want to fix for the current version of ATM.
